defaults: &defaults
  adapter: postgresql
  pool: 5
  timeout: 5000
  min_messages: WARNING

development:
  <<: *defaults
  database: coshx_development
  host: localhost

test: &test
  <<: *defaults
  database: coshx_test
  host: localhost

production:
  <<: *defaults
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *test
